// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AInput: typeof import('ant-design-vue/es')['Input']
    Button: typeof import('./src/components/cards/Button/Button.vue')['default']
    Input: typeof import('./src/components/cards/Input/Input.vue')['default']
  }
}

export { }
